[tasks.image1]
command = "docker"
args = ["build", "-t", "mysql-pinger1", "./pinger1/."]

[tasks.image2]
command = "docker"
args = ["build", "-t", "mysql-pinger2", "./pinger2/."]


[tasks.tag]
script = [
]

[tasks.push]
script = [
]

[tasks.install]
command = "cargo"
args = ["install", "--path", "."]

[tasks.package]
command = "cargo"
args = ["build", "--release"]

[tasks.version]
script = [
	"echo ${VERSION:? required}"
]

[tasks.precommit]
script = [
    "cargo fmt",
	# "cargo clippy"
]

[tasks.publish]
dependencies = [
	"version",
	# "image",
	# "tag",
	# "push",
    "precommit",
	"package"
]